### ISSUE TITLE
use image api for user profile image

### ISSUE THREAD

**Issue by boronflex** [matlittle/project-1-team-3#25]
use an api to return random image for user profile
Terry found a cool one:
https://robohash.org/

**Comment by matlittle** [comment]
*** Notes from Robohash website ***
For those inclined, there are several advanced techniques which have been added over time.

For Gravatar enthusiasts, you can ask Robohash to use a Gravatar if one is available.
Put either the email, or the hashed version, in your image where the string normally goes -

For example: https://robohash.org/colin@robohash.org?gravatar=yes
or https://robohash.org/620050a4db5104bae758cd75171d64ca?gravatar=hashed

We've also conditioned our robots to accept commands either via params or directories-
For instance https://robohash.org/set_set3/bgset_bg1/3.14159?size=500x500

**Comment by matlittle** [comment]
#43 Pull Request Approved
