### ISSUE TITLE
Function to set the user state, username, and avatar on successful login. 

### ISSUE THREAD

**Issue by matlittle** [matlittle/project-1-team-3#37]
We need a function that will set the user state to "active" when the login is successful, along with the username and avatar.

The avatar will be a simple URL, and will be generated by a separate function (Issue # tbd for that function).

**Comment by boronflex** [comment]
I'm going to start in on this portion, its handled when the login state turns true

**Comment by boronflex** [comment]
do the users get assigned one avatar on registering a new account?
or do they get a newly generated avatar everytime they log in

**Comment by matlittle** [comment]
#43 Pull Request Approved
